POST http://localhost:8080/battle HTTP/1.1
content-type: application/json

{
    "EnemyID":  "7fcbd1a2-ba12-4b1b-a4d5-c6b8dae7c684",
    "PlayerID": "825bc34b-6ef8-4070-84b1-46e5bf900e55"
}

###
GET http://localhost:8080/battle HTTP/1.1
content-type: application/json

{
}
