POST http://localhost:8080/battle HTTP/1.1
content-type: application/json

{
    "EnemyID":  "e8eaa794-b094-4040-831b-e7f4fd8fde4f",
    "PlayerID": "e963ebd9-e856-4c9d-8b94-89c3f1b36109"
}

###
GET http://localhost:8080/battle HTTP/1.1
content-type: application/json

{
}
