POST http://localhost:8080/enemy HTTP/1.1
content-type: application/json

{
    "nickname": "E6"
}

###

POST http://localhost:8080/enemy HTTP/1.1
content-type: application/json

{
    "nickname": "E7"
}

###
GET http://localhost:8080/enemy HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/enemy/fffd907d-a934-43b9-8ec4-cd56db4cc7e5 HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/enemy/7a3b9e2a-3097-4a0b-a18c-1f1b1ac6fd3f HTTP/1.1
content-type: application/json

{
}

###

PUT http://localhost:8080/enemy/7a3b9e2a-3097-4a0b-a18c-1f1b1ac6fd3f HTTP/1.1
content-type: application/json

{
    "nickname": "E3"
}

###

GET http://localhost:8080/enemy/7a3b9e2a-3097-4a0b-a18c-1f1b1ac6fd3f/repair-weapon HTTP/1.1
content-type: application/json

{
}