POST http://localhost:8080/enemy HTTP/1.1
content-type: application/json

{
    "nickname": "E1"
}

###

POST http://localhost:8080/enemy HTTP/1.1
content-type: application/json

{
    "nickname": "E2"
}

###
GET http://localhost:8080/enemy HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/enemy/47e23a4b-6152-40be-bccb-6e1f15921b45 HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/enemy/47e23a4b-6152-40be-bccb-6e1f15921b45 HTTP/1.1
content-type: application/json

{
}

###

PUT http://localhost:8080/enemy/47e23a4b-6152-40be-bccb-6e1f15921b45 HTTP/1.1
content-type: application/json

{
    "nickname": "E2"
}