POST http://localhost:8080/enemy HTTP/1.1
content-type: application/json

{
    "nickname": "A"
}

###
GET http://localhost:8080/enemy HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/enemy/b03fa00f-9aab-4995-b165-816697ef4ba8 HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/enemy/89008e13-6882-4de7-84cc-1f720f7a6900 HTTP/1.1
content-type: application/json

{
}

###

PUT http://localhost:8080/enemy/89008e13-6882-4de7-84cc-1f720f7a6900 HTTP/1.1
content-type: application/json

{
    "nickname": "K"
}