POST http://localhost:8080/player HTTP/1.1
content-type: application/json

{
    "nickname": "TheClipBR",
    "life": 10,
    "attack": 2
}

###
GET http://localhost:8080/player HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/player/e5396edb-5f20-4e90-8688-a12f63a8c895 HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/player/2116faf6-6da5-461b-a3db-c83263422e11 HTTP/1.1
content-type: application/json

{
}

###

PUT http://localhost:8080/player/2116faf6-6da5-461b-a3db-c83263422e11 HTTP/1.1
content-type: application/json

{
    "nickname": "TheClipBR",
    "attack": 1,
    "life": 1
}