POST http://localhost:8080/player HTTP/1.1
content-type: application/json

{
    "nickname": "P1",
    "life": 10,
    "weaponid": "177b7b6f-ba70-4dc9-aae6-a92c07a02a2e"
}

###
GET http://localhost:8080/player HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/player/825bc34b-6ef8-4070-84b1-46e5bf900e55 HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/player/825bc34b-6ef8-4070-84b1-46e5bf900e55 HTTP/1.1
content-type: application/json

{
}

###

PUT http://localhost:8080/player/825bc34b-6ef8-4070-84b1-46e5bf900e55 HTTP/1.1
content-type: application/json

{
    "nickname": "P1",
    "life": 100,
    "weaponid": "177b7b6f-ba70-4dc9-aae6-a92c07a02a2e"
}