POST http://localhost:8080/weapon HTTP/1.1
content-type: application/json

{
    "name": "Iron Sword",
    "attack": 4,
    "defense": 0.2,
    "durability": 6
}

###

POST http://localhost:8080/weapon HTTP/1.1
content-type: application/json

{
    "name": "Steel Sword",
    "attack": 6,
    "defense": 0.3,
    "durability": 8
}

###

POST http://localhost:8080/weapon HTTP/1.1
content-type: application/json

{
    "name": "Titanium Sword",
    "attack": 10,
    "defense": 0.5,
    "durability": 10
}

###

GET http://localhost:8080/weapon HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/weapon/33364d2e-5a4b-411e-9373-917f8bb34c90 HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/weapon/9b48bd04-d944-463b-be4e-a4eef73d7e15 HTTP/1.1
content-type: application/json

{
}

###

PUT http://localhost:8080/weapon/9b48bd04-d944-463b-be4e-a4eef73d7e15 HTTP/1.1
content-type: application/json

{
    "name": "Iron Sword",
    "attack": 5,
    "defense": 0.2,
    "durability": 7
}